"use client";
import { useEffect, useRef } from "react";

type Attr = { landing_page:string; source?:string; medium?:string; campaign?:string; referrer_domain?:string; ai_referral_source?:"chatgpt"|"other"; referral_category:"chatgpt"|"organic_search"|"direct"|"other_referral" };
const KEY="footplus_attribution";
declare global { interface Window { gtag?: (...args: unknown[]) => void } }
function host(ref: string) { try { return ref ? new URL(ref).hostname.replace(/^www\./,"") : undefined; } catch { return undefined; } }
function getAttr(): Attr { if (typeof window === "undefined") return { landing_page:"", referral_category:"direct"}; const stored=sessionStorage.getItem(KEY); if (stored) return JSON.parse(stored); const p=new URLSearchParams(location.search); const ref=host(document.referrer); const source=p.get("utm_source")||undefined; const medium=p.get("utm_medium")||undefined; const campaign=p.get("utm_campaign")||undefined; const chat=source?.toLowerCase().includes("chatgpt") || ref?.includes("chatgpt.com") || ref?.includes("openai.com"); const organic=medium==="organic" || ["google.com","bing.com","duckduckgo.com","yahoo.com"].some(d=>ref?.includes(d)); const attr={ landing_page:location.pathname, source, medium, campaign, referrer_domain:ref, ai_referral_source: chat?"chatgpt":ref?"other":undefined, referral_category: chat?"chatgpt":organic?"organic_search":ref?"other_referral":"direct" } satisfies Attr; sessionStorage.setItem(KEY, JSON.stringify(attr)); return attr; }
export function trackAdviceEvent(name:string, params:Record<string, unknown>) { if (typeof window === "undefined") return; const attr=getAttr(); window.gtag?.("event", name, { ...attr, ...params }); }
export default function AdviceTracker({ slug, title, category }: { slug:string; title:string; category:string }) { const sent=useRef(false); useEffect(()=>{ if(sent.current) return; sent.current=true; trackAdviceEvent("advice_article_view", { article_slug:slug, article_title:title, article_category:category, author:"Adam James" }); },[slug,title,category]); return null; }
export function AdviceTrackedLink({ href, children, eventName="advice_cta_click", params, className }: { href:string; children:React.ReactNode; eventName?:string; params:Record<string, unknown>; className?:string }) { return <a href={href} className={className} onClick={()=>trackAdviceEvent(eventName, { destination:href, ...params })}>{children}</a>; }
